name: CI

on:
  push:
    branches: ["main", "master"]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev,kokoro] || pip install .[kokoro] || pip install .
      - name: Run ruff
        run: ruff check src tests
      - name: Run black
        run: black --check src tests
      - name: Run mypy
        run: mypy src
      - name: Run pytest
        run: pytest -q
